spring.application.name=kanban-backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/kanban
spring.datasource.username=kanban_user
spring.datasource.password=kanban_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
